metadata-version = "2015-12-19"
log-level = "debug"
onetime = false
interval = 5

[[ template ]]
source = "/etc/rancher-conf/templates/state.yml.tmpl"
dest = "/etc/rancher-conf/haproxy/state.yml"
notify-cmd = "/etc/rancher-conf/scripts/generate-config"
poll-cmd = "/etc/rancher-conf/scripts/renew-certs"
